pipeline:
  - name: read_step
    op_key: read
    params:
      input_file:  resources/input_examples/search_protein_demo.jsonl # input file path, support json, jsonl, txt, pdf. See resources/input_examples for examples

  - name: search_step
    op_key: search
    deps: [read_step] # search_step depends on read_step
    params:
      data_sources: [uniprot] # data source for searcher, support: wikipedia, google, uniprot
      uniprot_params:
        use_local_blast: true # whether to use local blast for uniprot search
        local_blast_db: /your_path/2024_01/uniprot_sprot # format: /path/to/${RELEASE}/uniprot_sprot
        # options: uniprot_sprot (recommended, high quality), uniprot_trembl, or uniprot_${RELEASE} (merged database)
