pipeline:
  - name: read_step
    op_key: read
    params:
      input_file: resources/input_examples/txt_demo.txt  # input file path, support json, jsonl, txt, pdf. See resources/input_examples for examples

  - name: chunk_step
    op_key: chunk
    deps: [read_step] # chunk_step depends on read_step
    params:
        chunk_size: 1024 # chunk size for text splitting
        chunk_overlap: 100 # chunk overlap for text splitting

  - name: build_kg_step
    op_key: build_kg
    deps: [chunk_step] # build_kg depends on chunk_step

  - name: partition_step
    op_key: partition
    deps: [build_kg_step] # partition_step depends on build_kg
    params:
      method: leiden # leiden is a partitioner detection algorithm
      method_params:
        max_size: 20 # Maximum size of communities
        use_lcc: false # whether to use the largest connected component
        random_seed: 42 # random seed for partitioning

  - name: generate_step
    op_key: generate
    deps: [partition_step] # generate_step depends on partition_step
    params:
      method: cot # atomic, aggregated, multi_hop, cot, vqa
      data_format: Sharegpt # Alpaca, Sharegpt, ChatML
